### PR TITLE
Run multiple functions

### LINKED ISSUE #108: `shep run --all`
To put shep in a CI environment an `--all` flag would help. This would instruct shep to run all the functions against events and return a count of error'd functions (so it has a non zero exit code if anything fails)

### PR DESCRIPTION
**Pull request by chris-olszewski**
Closes #108.

### CODE REVIEW

File: src/run/index.js [hunk 1]
```diff
@@ -22,60 +22,81 @@ export default async function (opts) {
...
+  const out = await Promise.map(names, funcRunner)
+  out.map(loggingFunction)
+  console.log(ui.toString())
+
+  const failedFunctions = out.reduce((count, eventResponse) => {
+    return count + eventResponse.filter((e) => e.error).length
+  }, 0)
+
+  if (failedFunctions > 0) {
+    process.exit(failedFunctions)
```
Comment (reconbot) [inline src/run/index.js]: 👍

File: README.md [hunk 2]
```diff
@@ -134,7 +134,10 @@ Examples:
   shep run foo --no-build                Run the already built `foo` function in the dist folder
   shep run foo --event default           Runs the `foo` function for just the `default` event
   shep run foo --environment production  Runs the `foo` function with production environment
-  DB_TABLE=custom shep run foo           Runs the `foo` function with process.env.DB_TABLE assigned to custom (vars declared this way will overwrite vals in your environments/${env}.json file)
+  DB_TABLE=custom shep run foo           Runs the `foo` function with process.env.DB_TABLE assigned to custom (vars
+                                         declared this way will overwrite vals in your environments/${env}.json file)
+  shep run '*'                           Runs all functions for all events
+  shep run foo-*                         Runs all functions matching pattern `foo-*`
```
Comment (reconbot) [inline README.md]: probably need quotes here if there's a file named `foo-something` in the current directory
